### PR TITLE
Add Hive to the mix for testing

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Comment by samredai** [comment]
Hey @Fokko I'd like to get this in but what do you think about making a separate docker compose that uses spark and Iceberg configured with a Hive metastore?

The reason I ask is that I'm worried that including all of the many catalog implementations in the same docker compose might get confusing (for example is postgres used for a `JDBCCatalog` or is it backing an HMS and we're using the `HiveCatalog`?). It would be nice to have a single profile driven docker compose but maybe having separate setups for common combinations might be more consumable. I think Spark+HMS+HiveCatalog is probably the most popular combination and warrants it's own docker compose.

**Comment by Fokko** [comment]
Hey @samredai thanks for raising this, and I fully agree. I created this PR because someone in the community was looking for an example. I'm not sure if we should integrate this into the repository. There are much more mature catalogs such as the REST catalog. I can split this out for testing purposes (that's what I use it for).

**Comment by samredai** [comment]
Yeah this is awesome for testing hive, super useful. That's actually why I came to this PR--I checked it out locally and ran it and it worked great :)

**Comment by usbrandon** [comment]
Is there an updated version of this set up elsewhere?  I tried this one but could not connect to it externally.  I think setup files are missing.

**Comment by Fokko** [comment]
@usbrandon This is indeed an older version that worked with Hadoop, and we changed the backend to minio. I'm planning on giving this another try since I often use Hive for testing.

**Pull request closed without merging**
