### PR TITLE
Add new notebook showing how to do WAP with branches

### PR DESCRIPTION
**Pull request by rmoff**
This is based on the existing `Iceberg - Integrated Audits Demo.ipynb`, and shows how to use a branch-based approach for WAP.

### CODE REVIEW

**Comment by rdblue** [comment]
This looks great to me!

The only problem before I would publish this is that cherry-pick only works on one commit. You probably want to mention that where you call it out as "less elegant" (agreed!) because people may think that it would move more than one commit. Just note that it isn't a "rebase" maybe?

Also, thank you for taking the time @rmoff! Good to run into you again.

**Comment by rmoff** [comment]
Good point, thanks @rdblue - I've updated it.

**Comment by chrigehr** [comment]
Thank you for the work @rmoff , very helpful. 

I've been looking into branching and tagging capabilities of iceberg for some time now and was wondering if and how a wap approach could be used to handle duplicates. 
You create a branch and add new records there. Now there can be duplicates in the branch related to the main branch. So far I have thought about an "Insert into ...where not exists...." from the branch to main. But maybe there are smarter alternatives?!?

But probably this is the wrong place for such a discussion, sorry for that.

**Comment by rdblue** [comment]
@Fokko, can you help out here? This is failing validation but it looks good to me.

**Comment by rmoff** [comment]
Anything I can do here to help push this PR forward? :)

**Comment by rdblue** [comment]
@rmoff, the failure is this:

**Comment by Fokko** [comment]
@rmoff 

Please run:

```
pip3 install pre-commit
pre-commit run --all-files
```

Commit the changes, and this PR is ready to go :)

**Comment by rmoff** [comment]
@Fokko thanks - have pushed a change that should fix it.

**Comment by Fokko** [comment]
I just ran the notebook and it looks great! Thanks for contributing @rmoff ! 👏🏻

**Comment by rdblue** [comment]
Thanks, @rmoff!

**Pull request merged**
